name: Build pull request

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches:
      - "!main"

jobs:

  build_oh4:
    strategy:
      fail-fast: false
      matrix:
        java: [ '17' ]
        maven: [ '3.8.4' ]
        os: [ 'ubuntu-20.04' ]
    name: Build OH4 (Java ${{ matrix.java }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{matrix.java}}
          distribution: 'temurin'
      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.java }}-maven-

      - name: Build
        run: mvn -P 'standalone' --batch-mode -DskipChecks -Doh.java.version=17 clean verify
